# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb92d67ae81a616be94b786f5243935cf05e2142a72fe89669d361feea22f421bfc794cfcbe6e8883111f54dc532845b45182edaac108272045a7ff84d02de7c

test:
  secret_key_base: 1ac9d2f97e548f0f9eda92a318d2c137edc55025bdd55ec04e92ac3e4b447846bf4f105f36a2e633501e886a8d0c83fd0ad8d4758c7df8b3d91cdd3222709f37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
